In [ ]:
#import pakages required to read data from csv file
import pandas as pd
import numpy as np
from os import path

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/results/final_results.csv')
df

,name,correct_covid,wrong_covid,not_detected_covid,correct_pneu,wrong_pneu,not_detected_pneu,correct_normal,wrong_normal,not_detected_normal,...,pneu_num,normal_num,tp,fp,wrong_covid_normal,wrong_covid_pneu,wrong_pneu_covid,wrong_pneu_normal,wrong_normal_pneu,wrong_normal_covid
0,CNN,37,183,8,1845,316,575,4455,498,414,...,2420,4869,6337,997,2,6,79,496,310,104
1,InceptionV3,39,38,6,2184,199,236,4649,225,220,...,2420,4869,6872,462,1,5,12,224,194,26
2,Resnet50V2,38,32,7,2194,289,226,4565,216,304,...,2420,4869,6797,537,2,5,12,214,284,20
3,Xception,42,35,3,2162,188,258,4664,243,205,...,2420,4869,6868,466,2,1,17,241,187,18
4,Concatinated-Old,40,16,5,2236,313,184,4548,181,321,...,2420,4869,6824,510,2,3,5,179,310,11
5,Concatinated,44,36,1,2243,369,177,4479,163,390,...,2420,4869,6766,568,1,0,15,162,369,21

In [ ]:
df['Modal_Accuracy'] = (df['tp']/(df['fp']+df['tp']))* 100

In [ ]:
df['Covid_Accuracy'] = (((df['fp']+df['tp'])-df['covid_num']-df['wrong_covid']+df['correct_covid'])/((df['fp']+df['tp'])-df['covid_num']+df['correct_covid']+df['not_detected_covid']))*100
df['covid_Sensitivity']=(df['correct_covid']/df['covid_num'])*100
df['covid_Specificity']=(((df['fp']+df['tp'])-df['covid_num']-df['wrong_covid'])/((df['fp']+df['tp'])-df['covid_num']))*100

In [ ]:
df['Pnemonia_Sensitivity']=(df['correct_pneu']/df['pneu_num'])*100
df['Pnemonia_Accuracy'] = (((df['fp']+df['tp'])-df['pneu_num']-df['wrong_pneu']+df['correct_pneu'])/((df['fp']+df['tp'])-df['pneu_num']+df['correct_pneu']+df['not_detected_pneu']))*100
df['Pnemoia_Specificity']=(((df['fp']+df['tp'])-df['pneu_num']-df['wrong_pneu'])/((df['fp']+df['tp'])-df['pneu_num']))*100

In [ ]:
df['Normal_Sensitivity']=(df['correct_normal']/df['normal_num'])*100
df['Normal_Specificity']=(((df['fp']+df['tp'])-df['normal_num']-df['wrong_normal'])/((df['fp']+df['tp'])-df['normal_num']))*100
df['Normal_accuracy']=(((df['fp']+df['tp'])-df['normal_num']-df['wrong_normal']+df['correct_normal'])/((df['fp']+df['tp'])-df['normal_num']+df['correct_normal']+df['not_detected_normal']))*100

In [ ]:
df

,name,correct_covid,wrong_covid,not_detected_covid,correct_pneu,wrong_pneu,not_detected_pneu,correct_normal,wrong_normal,not_detected_normal,...,Covid_Accuracy,covid_Recall,covid_Specificity,Pnemonia_Recall,Pnemonia_Accuracy,Pnemoia_Specificity,Normal_Recall,Normal_Specificity,Normal_accuracy,Modal_Accuracy
0,CNN,37,183,8,1845,316,575,4455,498,414,...,0.973957,0.822222,0.974894,0.762397,0.878511,0.935694,0.914972,0.797972,0.875648,86.405781
1,InceptionV3,39,38,6,2184,199,236,4649,225,220,...,0.994001,0.866667,0.994787,0.902479,0.940687,0.959503,0.954816,0.908722,0.939324,93.700573
2,Resnet50V2,38,32,7,2194,289,226,4565,216,304,...,0.994682,0.844444,0.995610,0.906612,0.929779,0.941188,0.937564,0.912373,0.929097,92.677938
3,Xception,42,35,3,2162,188,258,4664,243,205,...,0.994819,0.933333,0.995198,0.893388,0.939187,0.961742,0.957897,0.901420,0.938915,93.646032
4,Concatinated-Old,40,16,5,2236,313,184,4548,181,321,...,0.997137,0.888889,0.997805,0.923967,0.932233,0.936304,0.934073,0.926572,0.931552,93.046087
5,Concatinated,44,36,1,2243,369,177,4479,163,390,...,0.994955,0.977778,0.995061,0.926860,0.925552,0.924908,0.919901,0.933874,0.924598,92.255250

In [ ]:
df.loc[:, ["name", "correct_covid",'not_detected_covid',"wrong_covid",'correct_pneu','not_detected_pneu','wrong_pneu','correct_normal','not_detected_normal','wrong_normal']]

,name,correct_covid,not_detected_covid,wrong_covid,correct_pneu,not_detected_pneu,wrong_pneu,correct_normal,not_detected_normal,wrong_normal
0,CNN,37,8,183,1845,575,316,4455,414,498
1,InceptionV3,39,6,38,2184,236,199,4649,220,225
2,Resnet50V2,38,7,32,2194,226,289,4565,304,216
3,Xception,42,3,35,2162,258,188,4664,205,243
4,Concatinated-Old,40,5,16,2236,184,313,4548,321,181
5,Concatinated,44,1,36,2243,177,369,4479,390,163

In [ ]:

df.loc[:, ["name","Modal_Accuracy","covid_Sensitivity","Pnemonia_Sensitivity","Normal_Sensitivity","covid_Specificity","Pnemoia_Specificity","Normal_Specificity","Covid_Accuracy","Pnemonia_Accuracy","Normal_accuracy"]]

,name,Modal_Accuracy,covid_Sensitivity,Pnemonia_Sensitivity,Normal_Sensitivity,covid_Specificity,Pnemoia_Specificity,Normal_Specificity,Covid_Accuracy,Pnemonia_Accuracy,Normal_accuracy
0,CNN,86.405781,82.222222,76.239669,91.497227,97.489368,93.569394,79.797160,97.395691,87.851104,87.564767
1,InceptionV3,93.700573,86.666667,90.247934,95.481618,99.478666,95.950346,90.872211,99.400055,94.068721,93.932370
2,Resnet50V2,92.677938,84.444444,90.661157,93.756418,99.560982,94.118844,91.237323,99.468230,92.977911,92.909735
3,Xception,93.646032,93.333333,89.338843,95.789690,99.519824,96.174196,90.141988,99.481865,93.918735,93.891464
4,Concatinated-Old,93.046087,88.888889,92.396694,93.407270,99.780491,93.630444,92.657201,99.713662,93.223343,93.155168
5,Concatinated,92.255250,97.777778,92.685950,91.990142,99.506105,92.490842,93.387424,99.495500,92.555222,92.459776